import React, { createContext, useState } from 'react';

export const LanguageContext = createContext();

export const translations = {
  pt: {
    "app.logged_as": "Logado como:",
    "sidebar.dashboard": "Dashboard",
    "sidebar.inventory": "Inventário",
    "sidebar.consultations": "Consultas",
    "sidebar.technical_sheets": "Fichas Técnicas",
    "sidebar.users": "Utilizadores",
    "sidebar.billing": "Faturação",
    "sidebar.reports": "Relatórios",
    "sidebar.light_mode": "Modo Claro",
    "sidebar.dark_mode": "Modo Escuro",
    "sidebar.settings": "Definições",
    "sidebar.logout": "Sair",
    "sidebar.patients": "Pacientes",
    
    "dashboard.title": "Dashboard MeClinic",
    "dashboard.subtitle": "Monitorização de desempenho semanal",
    "dashboard.week_of": "Semana de",
    "dashboard.card.new_patients": "NOVOS PACIENTES",
    "dashboard.card.new_patients_sub": "Registados esta semana",
    "dashboard.card.consultations": "CONSULTAS",
    "dashboard.card.consultations_sub": "Agendadas para a semana",
    "dashboard.card.billing": "FATURAÇÃO ESTIMADA",
    "dashboard.card.billing_sub": "Baseado nos procedimentos",
    "dashboard.card.stock_alerts": "ALERTAS DE STOCK",
    "dashboard.card.stock_alerts_sub": "Produtos abaixo do mínimo",
    "dashboard.chart.title": "Fluxo de Pacientes por Dia",
    "dashboard.modal.stock_title": "Produtos em Alerta de Stock",
    "dashboard.modal.stock_desc": "Estes materiais atingiram ou estão abaixo do limite mínimo.",
    "dashboard.modal.table.product": "Produto",
    "dashboard.modal.table.current": "Stock Atual",
    "dashboard.modal.table.min": "Mínimo",
    "dashboard.modal.close": "Fechar",
    "dashboard.modal.empty": "Nenhum produto em alerta.",
    "dashboard.card.expiry_alerts": "ALERTAS VALIDADE",
    "dashboard.card.expiry_alerts_sub": "A caducar em < 30 dias",
    "dashboard.modal.expiry_title": "Produtos a Caducar",
    "dashboard.modal.expiry_desc": "Estes materiais expiram nos próximos 30 dias ou já caducaram.",
    "dashboard.modal.table.category": "Categoria",
    "dashboard.modal.table.expiry": "Validade",
    "dashboard.modal.btn_order": "Gerar Encomenda (PDF)",
    "dashboard.order.title": "NOTA DE ENCOMENDA",
    "dashboard.order.date": "Data:",
    "dashboard.order.product": "Produto",
    "dashboard.order.current": "Stock Atual",
    "dashboard.order.suggested": "Qtd Encomendar",
    "dashboard.order.signature": "Assinatura do Responsável:",

    "inventory.title": "Inventário",
    "inventory.subtitle": "Vista de cartões e leitura de código de barras.",
    "inventory.btn.camera": "Ler Código (Câmara)",
    "inventory.btn.add": "Adicionar Produto",
    "inventory.search.placeholder": "Pesquisar produto ou digitar código...",
    "inventory.card.no_code": "SEM CÓDIGO",
    "inventory.card.current_qty": "QTD ATUAL",
    "inventory.card.total_calc": "no total",
    "inventory.empty": "Nenhum produto encontrado.",
    "inventory.modal.add_title": "Novo Produto",
    "inventory.modal.edit_title": "Editar Produto",
    "inventory.modal.name": "Nome do Produto",
    "inventory.modal.name_ph": "Ex: Luvas de Nitrilo",
    "inventory.modal.barcode": "Código de Barras",
    "inventory.modal.barcode_ph": "Opcional...",
    "inventory.modal.unit": "Unidade de Medida",
    "inventory.modal.unit.un": "Unidades (un)",
    "inventory.modal.unit.cx": "Caixas (cx)",
    "inventory.modal.unit.mts": "Metros (mts)",
    "inventory.modal.unit.lts": "Litros (lts)",
    "inventory.modal.unit.ml": "Mililitros (ml)",
    "inventory.modal.unit.grs": "Gramas (grs)",
    "inventory.modal.stock_current": "Stock Atual",
    "inventory.modal.stock_min": "Stock Mínimo (Alerta)",
    "inventory.modal.img_url": "URL da Imagem (Link da net)",
    "inventory.modal.img_url_ph": "https://...",
    "inventory.modal.cancel": "Cancelar",
    "inventory.modal.save": "Guardar",
    "inventory.delete.title": "Remover Produto?",
    "inventory.delete.desc": "Esta ação vai apagar o produto permanentemente do inventário.",
    "inventory.delete.cancel": "Cancelar",
    "inventory.delete.confirm": "Remover",
    "inventory.alert.success": "Sucesso!",
    "inventory.alert.warning": "Atenção",
    "inventory.alert.btn_ok": "OK, entendi",
    "inventory.msg.removed": "Produto removido com sucesso.",
    "inventory.msg.remove_err": "Erro ao remover produto.",
    "inventory.msg.server_err": "Falha ao ligar ao servidor.",
    "inventory.msg.added": "Produto adicionado ao inventário!",
    "inventory.msg.updated": "Produto atualizado!",
    "inventory.msg.save_err": "Erro ao guardar produto.",
    "inventory.cat.all": "Todas as Categorias",
    "inventory.cat.disposables": "Descartáveis",
    "inventory.cat.anesthesia": "Anestesia & Fármacos",
    "inventory.cat.endo": "Endo & Restauração",
    "inventory.cat.surgery": "Cirurgia & Implantes",
    "inventory.cat.ortho": "Ortodontia",
    "inventory.cat.sterilization": "Esterilização",
    "inventory.cat.instruments": "Instrumentos",
    "inventory.modal.category": "Categoria do Produto",
    "inventory.modal.expiry": "Data de Validade",
    "inventory.modal.expiry_ph": "Opcional...",

    "tech_sheets.title": "Fichas Técnicas",
    "tech_sheets.btn.new": "Novo Procedimento",
    "tech_sheets.list.price": "Preço Venda:",
    "tech_sheets.list.empty": "Nenhum procedimento criado.",
    "tech_sheets.modal.new_title": "Novo Procedimento",
    "tech_sheets.modal.new_ph": "Nome da ficha técnica...",
    "tech_sheets.modal.cancel": "Cancelar",
    "tech_sheets.modal.create": "Criar",
    "tech_sheets.delete.title": "Apagar Procedimento?",
    "tech_sheets.delete.desc_part1": "Tem a certeza que deseja remover a ficha de",
    "tech_sheets.delete.desc_part2": "Esta ação apaga os materiais associados.",
    "tech_sheets.delete.remove": "Remover",
    "tech_sheets.detail.edit": "Editar",
    "tech_sheets.detail.remove": "Remover",
    "tech_sheets.detail.export": "Exportar PDF",
    "tech_sheets.detail.cancel": "Cancelar",
    "tech_sheets.detail.save": "Guardar Alterações",
    "tech_sheets.table.material": "Material Utilizado",
    "tech_sheets.table.qty": "Qtd",
    "tech_sheets.table.cost_un": "Custo Un.",
    "tech_sheets.table.subtotal": "Subtotal",
    "tech_sheets.table.ph_material": "Nome do material...",
    "tech_sheets.btn.add_material": "Adicionar Novo Material",
    "tech_sheets.summary.cost": "Custo Materiais",
    "tech_sheets.summary.price": "Preço a Cobrar",
    "tech_sheets.empty_state.title": "Nenhuma ficha selecionada",
    "tech_sheets.empty_state.desc": "Selecione um procedimento na lista à esquerda para visualizar os materiais e custos associados.",
    "tech_sheets.msg.created": "Procedimento criado!",
    "tech_sheets.msg.removed": "Procedimento removido com sucesso!",
    "tech_sheets.msg.remove_err": "Erro ao remover procedimento.",
    "tech_sheets.msg.saved": "Ficha atualizada e guardada!",
    "tech_sheets.msg.save_err": "Erro ao salvar a ficha técnica.",

    "consultations.title": "Gestão de Consultas",
    "consultations.form.new": "Nova Marcação",
    "consultations.form.edit": "Editar Marcação",
    "consultations.form.name_ph": "Nome do Paciente",
    "consultations.form.email_ph": "E-mail (Recomendado)",
    "consultations.form.phone_ph": "Ex: 912345678",
    "consultations.form.procedure": "Procedimento Clínico",
    "consultations.form.procedure_ph": "Selecione um procedimento...",
    "consultations.form.date": "Data",
    "consultations.form.time": "Hora",
    "consultations.form.notes": "Notas Adicionais...",
    "consultations.form.notes_ph": "Opcional...",
    "consultations.form.btn_confirm": "Confirmar Agenda",
    "consultations.form.btn_save": "Guardar Alterações",
    "consultations.form.btn_cancel": "Cancelar Edição",
    "consultations.list.title": "Marcações",
    "consultations.list.filter_today": "Hoje",
    "consultations.list.filter_week": "7 Dias",
    "consultations.list.filter_month": "30 Dias",
    "consultations.list.empty": "Nenhuma marcação encontrada para este período.",
    "consultations.list.finished": "Finalizada",
    "consultations.list.no_procedure": "Sem Procedimento",
    "consultations.list.no_phone": "Sem número",
    "consultations.tooltip.finish": "Finalizar Consulta",
    "consultations.tooltip.edit": "Editar",
    "consultations.tooltip.delete": "Desmarcar",
    "consultations.checkout.title": "Finalizar Consulta",
    "consultations.checkout.patient": "Paciente:",
    "consultations.checkout.procedure": "Procedimento:",
    "consultations.checkout.payment_method": "Método de Pagamento",
    "consultations.checkout.multibanco": "Multibanco",
    "consultations.checkout.mbway": "MB Way",
    "consultations.checkout.cash": "Numerário",
    "consultations.checkout.transfer": "Transferência Bancária",
    "consultations.checkout.send_email": "Enviar recibo por e-mail",
    "consultations.checkout.email_ph": "Introduza o e-mail do paciente...",
    "consultations.checkout.cancel": "Cancelar",
    "consultations.checkout.confirm": "Confirmar Pagamento",
    "consultations.checkout.processing": "A processar...",
    "consultations.delete.title": "Atenção!",
    "consultations.delete.desc": "Tem a certeza que quer desmarcar e apagar esta consulta? Esta ação não pode ser revertida.",
    "consultations.delete.cancel": "Cancelar",
    "consultations.delete.confirm": "Eliminar",
    "consultations.pdf.title": "NOTA DE HONORÁRIOS",
    "consultations.pdf.subtitle": "DOCUMENTO DE CONTROLO INTERNO",
    "consultations.pdf.patient": "Paciente: ",
    "consultations.pdf.datetime": "Data/Hora: ",
    "consultations.pdf.procedure": "Procedimento: ",
    "consultations.pdf.payment": "Método Pag.: ",
    "consultations.pdf.total": "TOTAL PAGO: ",
    "consultations.general": "Consulta Geral",
    "consultations.msg.updated": "Consulta atualizada!",
    "consultations.msg.scheduled": "Consulta agendada!",
    "consultations.msg.save_err": "Erro ao salvar.",
    "consultations.msg.deleted": "Consulta apagada com sucesso.",
    "consultations.msg.delete_err": "Erro ao apagar consulta.",
    "consultations.msg.checkout_success": "Consulta finalizada com sucesso!",
    "consultations.msg.checkout_err": "Erro ao finalizar no servidor.",
    "consultations.msg.comm_err": "Erro de comunicação.",
    "consultations.view.list": "Lista",
    "consultations.view.calendar": "Calendário",
    "consultations.checkout.materials": "Materiais Utilizados (Ajuste se necessário)",
    "consultations.checkout.no_materials": "Nenhum material previsto para este procedimento.",
    "consultations.checkout.upload_exam": "Anexar Exame / Documento (Opcional)",
    "consultations.checkout.rx_title": "Receita & Recomendações (Opcional)",
    "consultations.checkout.recs": "Recomendações Pós-Consulta",
    "consultations.checkout.recs_ph": "Ex: Não mastigar alimentos duros nas próximas 2h. Colocar gelo...",
    "consultations.list.reminder": "Enviar Lembrete (WhatsApp)",

    "users.title": "Acessos e Equipa",
    "users.subtitle": "Gere quem tem acesso ao sistema da clínica.",
    "users.btn.add": "Adicionar Membro",
    "users.search.placeholder": "Pesquisar por nome ou email...",
    "users.card.you": "TU",
    "users.card.offline": "OFFLINE",
    "users.card.role.assistant": "Assistente",
    "users.card.role.admin": "Admin",
    "users.card.tooltip.remove": "Remover Utilizador",
    "users.empty": "Nenhum utilizador encontrado com essa pesquisa.",
    "users.delete.title": "Remover Utilizador?",
    "users.delete.desc": "O acesso deste membro será revogado permanentemente.",
    "users.delete.cancel": "Cancelar",
    "users.delete.confirm": "Remover",
    "users.modal.title": "Novo Membro",
    "users.modal.name": "Nome Completo",
    "users.modal.name_ph": "Ex: Dra. Ana Silva",
    "users.modal.email": "Endereço de E-mail",
    "users.modal.email_ph": "ana.silva@meclinic.com",
    "users.modal.pass": "Palavra-Passe Inicial",
    "users.modal.pass_ph": "Uma password para o primeiro acesso...",
    "users.modal.role": "Função no Sistema (Acesso)",
    "users.modal.role.assistant_desc": "Agenda e Consultas",
    "users.modal.role.admin_desc": "Acesso Total e Financeiro",
    "users.modal.cancel": "Cancelar",
    "users.modal.create": "Criar Membro",
    "users.modal.creating": "A Criar...",
    "users.mfa.title": "Segurança Obrigatória (MFA)",
    "users.mfa.desc": "O membro foi criado. Peça a essa pessoa para abrir a App Google Authenticator e ler este código agora mesmo.",
    "users.mfa.btn": "Concluir Registo",
    "users.msg.del_self": "Não podes apagar a tua própria conta enquanto tens sessão iniciada.",
    "users.msg.removed": "Utilizador removido do sistema com sucesso.",
    "users.msg.remove_err": "Erro ao remover utilizador.",
    "users.msg.added": "Membro adicionado com sucesso!",
    "users.msg.add_err": "Erro ao criar utilizador.",

    "billing.title": "Histórico e Faturação",
    "billing.subtitle": "Registo financeiro interno de todas as consultas finalizadas.",
    "billing.dashboard.total": "Total Cobrado",
    "billing.dashboard.processed": "consultas processadas",
    "billing.filter.title": "Filtrar Histórico",
    "billing.filter.today": "Hoje",
    "billing.filter.week": "Últimos 7 Dias",
    "billing.filter.month": "Este Mês",
    "billing.filter.all": "Todo o Histórico",
    "billing.table.date": "DATA / HORA",
    "billing.table.patient": "PACIENTE",
    "billing.table.procedure": "PROCEDIMENTO",
    "billing.table.method": "MÉTODO",
    "billing.table.value": "VALOR",
    "billing.table.note": "NOTA",
    "billing.table.tooltip": "Ver Nota de Faturação",
    "billing.table.empty": "Nenhum registo financeiro encontrado para este período.",
    "billing.modal.title": "Nota de Honorários",
    "billing.modal.subtitle": "DOCUMENTO DE CONTROLO INTERNO",
    "billing.modal.patient": "Paciente:",
    "billing.modal.datetime": "Data e Hora:",
    "billing.modal.procedure": "Procedimento(s):",
    "billing.modal.method": "Método Pag.:",
    "billing.modal.total": "TOTAL LIQUIDADO",
    "billing.modal.btn_close": "Fechar",
    "billing.modal.btn_print": "Imprimir Nota",

    "reports.title": "Relatório Financeiro",
    "reports.subtitle": "Análise de desempenho e custos.",
    "reports.week_of": "Semana de",
    "reports.btn.print": "Imprimir Relatório",
    "reports.btn.send_email": "Enviar para Admin",
    "reports.btn.sending": "A enviar...",
    "reports.card.consultations": "Consultas Concluídas",
    "reports.card.billed": "Total Faturado",
    "reports.card.materials": "Custo de Materiais",
    "reports.card.profit": "Lucro Bruto Estimado",
    "reports.table.procedures": "Procedimentos Realizados",
    "reports.table.proc.name": "NOME",
    "reports.table.proc.qty": "QTD",
    "reports.table.proc.value": "VALOR FATURADO",
    "reports.table.materials": "Consumo de Materiais",
    "reports.table.mat.name": "MATERIAL",
    "reports.table.mat.qty": "QTD",
    "reports.table.mat.cost_un": "CUSTO UN.",
    "reports.table.mat.cost_total": "CUSTO TOTAL",
    "reports.empty": "Sem dados nesta semana.",
    "reports.loading": "A carregar dados do relatório...",
    "reports.pdf.title": "Resumo Financeiro",
    "reports.pdf.consultations": "Consultas Realizadas:",
    "reports.pdf.billed": "Total Faturado:",
    "reports.pdf.materials": "Custo de Materiais:",
    "reports.pdf.profit": "Lucro Bruto Estimado:",
    "reports.pdf.table.proc": "Procedimento Realizado",
    "reports.pdf.table.mat": "Material Gasto",
    "reports.msg.success": "Relatório enviado com sucesso para o seu e-mail",
    "reports.msg.email_err": "Erro: Não foi possível encontrar o seu e-mail na base de dados.",
    "reports.msg.send_err": "Erro ao enviar. Verifique a palavra-passe de aplicação do Gmail no servidor.",
    "reports.msg.server_err": "Falha ao conectar ao servidor.",
    "reports.alert.success": "Sucesso!",
    "reports.alert.warning": "Aviso do Sistema",
    "reports.alert.btn_ok": "OK, entendi",

    "settings.title": "Definições Gerais",
    "settings.subtitle": "Gere as tuas preferências, interface e segurança da conta.",
    "settings.tab.profile": "O Meu Perfil",
    "settings.tab.security": "Segurança & MFA",
    "settings.tab.appearance": "Aparência e Interface",
    "settings.tab.notifications": "Notificações",
    "settings.tab.clinic": "Dados da Clínica",
    "settings.profile.title": "O Meu Perfil",
    "settings.profile.avatar_desc": "A tua fotografia é gerada automaticamente com base no teu nome.",
    "settings.profile.name": "Nome Completo",
    "settings.profile.email": "Endereço de E-mail",
    "settings.profile.contact_admin": "Contacta o Administrador para alterar dados sensíveis da conta.",
    "settings.security.title": "Segurança & Autenticação",
    "settings.security.mfa_active": "Autenticação de 2 Fatores (MFA) Ativa",
    "settings.security.mfa_desc": "A tua conta está protegida. O telemóvel é obrigatório para fazer alterações.",
    "settings.security.current_pass": "Palavra-passe Atual",
    "settings.security.new_pass": "Nova Palavra-passe",
    "settings.security.confirm_pass": "Confirmar Nova",
    "settings.security.mfa_code": "Código Google Authenticator",
    "settings.security.mfa_code_desc": "Insere o código de 6 dígitos gerado pela aplicação.",
    "settings.security.placeholder.current": "••••••••",
    "settings.security.placeholder.new": "Mín. 8 caracteres",
    "settings.security.placeholder.confirm": "Repita a password",
    "settings.appearance.title": "Aparência e Interface",
    "settings.appearance.theme": "Tema do Sistema",
    "settings.appearance.light": "Modo Claro",
    "settings.appearance.light_desc": "Design limpo para ambientes iluminados.",
    "settings.appearance.dark": "Modo Escuro",
    "settings.appearance.dark_desc": "Ambiente focado que descansa a vista.",
    "settings.appearance.location": "Localização",
    "settings.appearance.language": "Idioma da Interface",
    "settings.appearance.time_format": "Formato de Hora",
    "lang.pt": "Português (Portugal)",
    "lang.en": "English (United States)",
    "lang.es": "Español (España)",
    "time.24h": "24 Horas (14:30)",
    "time.12h": "12 Horas (02:30 PM)",
    "settings.notif.title": "Preferências de Alertas",
    "settings.notif.stock": "Alertas de Stock Baixo",
    "settings.notif.stock_desc": "Recebe notificações na plataforma quando um material atinge o limite mínimo definido no inventário.",
    "settings.notif.reports": "Resumo Financeiro Semanal",
    "settings.notif.reports_desc": "Envia um PDF com o relatório de faturação para o teu e-mail de forma automática todas as sextas-feiras.",
    "settings.notif.consultations": "Lembretes de Consultas",
    "settings.notif.consultations_desc": "Recebe um aviso no telemóvel/computador 15 minutos antes de uma consulta começar.",
    "settings.clinic.title": "Dados Oficiais da Entidade",
    "settings.clinic.readonly": "Modo Leitura",
    "settings.clinic.entity_name": "Nome da Entidade",
    "settings.clinic.nif": "NIF",
    "settings.clinic.phone": "Telefone Principal",
    "settings.clinic.email": "E-mail Geral",
    "settings.clinic.address": "Morada Completa",
    "settings.clinic.address_desc": "Esta informação é utilizada no cabeçalho das Fichas Técnicas e Relatórios.",
    "settings.btn.save": "Guardar Alterações",
    "settings.btn.update_security": "Atualizar Segurança",
    "settings.alert.success": "Definições guardadas com sucesso!",
    "settings.alert.clinic_success": "Dados da entidade atualizados com sucesso!",
    "settings.alert.pass_empty": "Preencha todos os campos da palavra-passe.",
    "settings.alert.pass_mismatch": "A nova palavra-passe e a confirmação não coincidem.",
    "settings.alert.mfa_empty": "Por favor, insira o código do Google Authenticator.",
    "settings.alert.server_error": "Erro ao ligar ao servidor.",
    "settings.privacy.title": "Privacidade & Conformidade GDPR",
    "settings.privacy.protection": "Proteção de Dados",
    "settings.privacy.protection_desc": "Os teus dados são protegidos de acordo com o Regulamento Geral de Proteção de Dados (RGPD).",
    "settings.privacy.download": "Descarregar Dados Pessoais",
    "settings.privacy.download_desc": "Descarrega uma cópia de todos os teus dados pessoais em formato JSON.",
    "settings.privacy.delete": "Eliminar Conta",
    "settings.privacy.delete_desc": "A eliminação da tua conta é permanente e removerá todos os teus dados do sistema.",
    "settings.privacy.delete_confirm": "Eliminar Conta Permanentemente",
    "settings.privacy.compliance": "Conformidade RGPD Completa",
    "settings.activity.title": "Atividade da Conta",
    "settings.activity.sessions": "Sessões Ativas",
    "settings.activity.devices": "Dispositivos Conectados",
    "settings.activity.current_device": "Este Dispositivo (atual)",
    "settings.activity.logout_all": "Desconectar Todos os Dispositivos",
    "settings.activity.history": "Últimos Logins",
    "settings.activity.location": "Localização",
    "settings.activity.device_info": "Dispositivo",

    "auth.login.title": "Bem-vindo de volta",
    "auth.login.subtitle": "Introduza as suas credenciais para aceder.",
    "auth.login.email": "E-mail",
    "auth.login.pass": "Palavra-passe",
    "auth.login.mfa": "Código Google Authenticator",
    "auth.login.btn": "Entrar no Sistema",
    "auth.login.forgot": "Esqueceu a sua palavra-passe?",
    "auth.register.title": "Criar Conta",
    "auth.register.subtitle": "Registe-se no portal de gestão clínica.",
    "auth.register.name": "Nome Completo",
    "auth.register.btn": "Registar Conta",
    "auth.switch.login": "Já tem conta? Iniciar Sessão",
    "auth.switch.register": "Não tem conta? Registe-se aqui",
    "auth.success.created": "Conta criada com sucesso!",
    "auth.success.mfa_desc": "Leia este QR Code com a sua App Google Authenticator para ativar a segurança da conta.",
    "auth.success.btn_login": "Ir para o Login",
    "auth.forgot.title": "Recuperar Palavra-passe",
    "auth.forgot.subtitle": "Insira o seu e-mail para receber um código de segurança.",
    "auth.forgot.btn": "Enviar Código",
    "auth.forgot.back": "Voltar ao Login",
    "auth.reset.title": "Nova Palavra-passe",
    "auth.reset.subtitle": "Insira o código que recebeu no e-mail e a nova palavra-passe.",
    "auth.reset.code": "Código de 6 dígitos",
    "auth.reset.new_pass": "Nova Palavra-passe",
    "auth.reset.btn": "Alterar Palavra-passe",
    "auth.reset.confirm_pass": "Confirmar Palavra-passe",
    "auth.reset.mismatch": "As palavras-passe não coincidem.",

    // --- PACIENTES (CRM) ---
    "patients.title": "Pacientes",
    "patients.subtitle": "Gestão de fichas clínicas e histórico.",
    "patients.search": "Pesquisar paciente...",
    "patients.table.name": "Nome",
    "patients.table.contact": "Contacto",
    "patients.table.consultations": "Consultas",
    "patients.table.billed": "Faturado",
    "patients.modal.info": "Ficha do Paciente",
    "patients.modal.notes": "Notas Clínicas",
    "patients.modal.notes_ph": "Escreva aqui alergias, histórico médico ou detalhes de tratamentos...",
    "patients.modal.history": "Histórico de Consultas",
    "patients.modal.save_notes": "Guardar Notas",
    "patients.modal.empty_history": "Nenhuma consulta registada.",
    "patients.tabs.history": "Histórico",
    "patients.tabs.exams": "Exames & Ficheiros",
    "patients.exams.upload": "Anexar Documento",
    "patients.exams.empty": "Nenhum documento anexado.",
    "patients.delete.btn": "Eliminar Paciente",
    "patients.delete.confirm": "Tem a certeza? Isto apagará o paciente, consultas e exames permanentemente.",
    "patients.table.actions": "Ações",
    "patients.rx.btn": "Passar Receita",
    "patients.rx.title": "Nova Receita Médica",
    "patients.rx.med": "Medicamento (ex: Ibuprofeno 600mg)",
    "patients.rx.dos": "Posologia (ex: 1 comp. de 8 em 8 horas)",
    "patients.rx.add": "Adicionar Medicamento",
    "patients.rx.generate": "Gerar & Guardar Receita",
  },
  en: {
    "app.logged_as": "Logged in as:",
    "sidebar.dashboard": "Dashboard",
    "sidebar.inventory": "Inventory",
    "sidebar.consultations": "Appointments",
    "sidebar.technical_sheets": "Tech Sheets",
    "sidebar.users": "Users",
    "sidebar.billing": "Billing",
    "sidebar.reports": "Reports",
    "sidebar.light_mode": "Light Mode",
    "sidebar.dark_mode": "Dark Mode",
    "sidebar.settings": "Settings",
    "sidebar.logout": "Logout",
    "sidebar.patients": "Patients",

    "dashboard.title": "MeClinic Dashboard",
    "dashboard.subtitle": "Weekly performance monitoring",
    "dashboard.week_of": "Week of",
    "dashboard.card.new_patients": "NEW PATIENTS",
    "dashboard.card.new_patients_sub": "Registered this week",
    "dashboard.card.consultations": "APPOINTMENTS",
    "dashboard.card.consultations_sub": "Scheduled for the week",
    "dashboard.card.billing": "ESTIMATED REVENUE",
    "dashboard.card.billing_sub": "Based on procedures",
    "dashboard.card.stock_alerts": "STOCK ALERTS",
    "dashboard.card.stock_alerts_sub": "Items below minimum",
    "dashboard.chart.title": "Patient Flow per Day",
    "dashboard.modal.stock_title": "Products in Stock Alert",
    "dashboard.modal.stock_desc": "These materials have reached or are below the minimum limit.",
    "dashboard.modal.table.product": "Product",
    "dashboard.modal.table.current": "Current Stock",
    "dashboard.modal.table.min": "Minimum",
    "dashboard.modal.close": "Close",
    "dashboard.modal.empty": "No products in alert.",
    "dashboard.card.expiry_alerts": "EXPIRY ALERTS",
    "dashboard.card.expiry_alerts_sub": "Expiring in < 30 days",
    "dashboard.modal.expiry_title": "Expiring Products",
    "dashboard.modal.expiry_desc": "These materials will expire in the next 30 days or have already expired.",
    "dashboard.modal.table.category": "Category",
    "dashboard.modal.table.expiry": "Expiry Date",
    "dashboard.modal.btn_order": "Generate Order (PDF)",
    "dashboard.order.title": "PURCHASE ORDER",
    "dashboard.order.date": "Date:",
    "dashboard.order.product": "Product",
    "dashboard.order.current": "Current Stock",
    "dashboard.order.suggested": "Qty to Order",
    "dashboard.order.signature": "Authorized Signature:",

    "inventory.title": "Inventory",
    "inventory.subtitle": "Card view and barcode scanning.",
    "inventory.btn.camera": "Scan Barcode (Camera)",
    "inventory.btn.add": "Add Product",
    "inventory.search.placeholder": "Search product or type code...",
    "inventory.card.no_code": "NO CODE",
    "inventory.card.current_qty": "CURRENT QTY",
    "inventory.card.total_calc": "in total",
    "inventory.empty": "No products found.",
    "inventory.modal.add_title": "New Product",
    "inventory.modal.edit_title": "Edit Product",
    "inventory.modal.name": "Product Name",
    "inventory.modal.name_ph": "Ex: Nitrile Gloves",
    "inventory.modal.barcode": "Barcode",
    "inventory.modal.barcode_ph": "Optional...",
    "inventory.modal.unit": "Unit of Measure",
    "inventory.modal.unit.un": "Units (un)",
    "inventory.modal.unit.cx": "Boxes (bx)",
    "inventory.modal.unit.mts": "Meters (m)",
    "inventory.modal.unit.lts": "Liters (L)",
    "inventory.modal.unit.ml": "Milliliters (ml)",
    "inventory.modal.unit.grs": "Grams (g)",
    "inventory.modal.stock_current": "Current Stock",
    "inventory.modal.stock_min": "Minimum Stock (Alert)",
    "inventory.modal.img_url": "Image URL (Web link)",
    "inventory.modal.img_url_ph": "https://...",
    "inventory.modal.cancel": "Cancel",
    "inventory.modal.save": "Save",
    "inventory.delete.title": "Remove Product?",
    "inventory.delete.desc": "This action will permanently delete the product from the inventory.",
    "inventory.delete.cancel": "Cancel",
    "inventory.delete.confirm": "Remove",
    "inventory.alert.success": "Success!",
    "inventory.alert.warning": "Warning",
    "inventory.alert.btn_ok": "OK, got it",
    "inventory.msg.removed": "Product removed successfully.",
    "inventory.msg.remove_err": "Error removing product.",
    "inventory.msg.server_err": "Failed to connect to server.",
    "inventory.msg.added": "Product added to inventory!",
    "inventory.msg.updated": "Product updated!",
    "inventory.msg.save_err": "Error saving product.",
    "inventory.cat.all": "All Categories",
    "inventory.cat.disposables": "Disposables",
    "inventory.cat.anesthesia": "Anesthesia & Pharma",
    "inventory.cat.endo": "Endo & Restoration",
    "inventory.cat.surgery": "Surgery & Implants",
    "inventory.cat.ortho": "Orthodontics",
    "inventory.cat.sterilization": "Sterilization",
    "inventory.cat.instruments": "Instruments",
    "inventory.modal.category": "Product Category",
    "inventory.modal.expiry": "Expiration Date",
    "inventory.modal.expiry_ph": "Optional...",

    "tech_sheets.title": "Technical Sheets",
    "tech_sheets.btn.new": "New Procedure",
    "tech_sheets.list.price": "Selling Price:",
    "tech_sheets.list.empty": "No procedures created.",
    "tech_sheets.modal.new_title": "New Procedure",
    "tech_sheets.modal.new_ph": "Technical sheet name...",
    "tech_sheets.modal.cancel": "Cancel",
    "tech_sheets.modal.create": "Create",
    "tech_sheets.delete.title": "Delete Procedure?",
    "tech_sheets.delete.desc_part1": "Are you sure you want to remove the sheet for",
    "tech_sheets.delete.desc_part2": "This action deletes associated materials.",
    "tech_sheets.delete.remove": "Remove",
    "tech_sheets.detail.edit": "Edit",
    "tech_sheets.detail.remove": "Remove",
    "tech_sheets.detail.export": "Export PDF",
    "tech_sheets.detail.cancel": "Cancel",
    "tech_sheets.detail.save": "Save Changes",
    "tech_sheets.table.material": "Material Used",
    "tech_sheets.table.qty": "Qty",
    "tech_sheets.table.cost_un": "Unit Cost",
    "tech_sheets.table.subtotal": "Subtotal",
    "tech_sheets.table.ph_material": "Material name...",
    "tech_sheets.btn.add_material": "Add New Material",
    "tech_sheets.summary.cost": "Material Cost",
    "tech_sheets.summary.price": "Price to Charge",
    "tech_sheets.empty_state.title": "No sheet selected",
    "tech_sheets.empty_state.desc": "Select a procedure from the list on the left to view associated materials and costs.",
    "tech_sheets.msg.created": "Procedure created!",
    "tech_sheets.msg.removed": "Procedure removed successfully!",
    "tech_sheets.msg.remove_err": "Error removing procedure.",
    "tech_sheets.msg.saved": "Sheet updated and saved!",
    "tech_sheets.msg.save_err": "Error saving the technical sheet.",

    "consultations.title": "Appointments Management",
    "consultations.form.new": "New Appointment",
    "consultations.form.edit": "Edit Appointment",
    "consultations.form.name_ph": "Patient Name",
    "consultations.form.email_ph": "Email (Recommended)",
    "consultations.form.phone_ph": "Ex: 912345678",
    "consultations.form.procedure": "Clinical Procedure",
    "consultations.form.procedure_ph": "Select a procedure...",
    "consultations.form.date": "Date",
    "consultations.form.time": "Time",
    "consultations.form.notes": "Additional Notes...",
    "consultations.form.notes_ph": "Optional...",
    "consultations.form.btn_confirm": "Confirm Schedule",
    "consultations.form.btn_save": "Save Changes",
    "consultations.form.btn_cancel": "Cancel Edit",
    "consultations.list.title": "Appointments",
    "consultations.list.filter_today": "Today",
    "consultations.list.filter_week": "7 Days",
    "consultations.list.filter_month": "30 Days",
    "consultations.list.empty": "No appointments found for this period.",
    "consultations.list.finished": "Finished",
    "consultations.list.no_procedure": "No Procedure",
    "consultations.list.no_phone": "No phone number",
    "consultations.tooltip.finish": "Finish Appointment",
    "consultations.tooltip.edit": "Edit",
    "consultations.tooltip.delete": "Cancel Appointment",
    "consultations.checkout.title": "Finish Appointment",
    "consultations.checkout.patient": "Patient:",
    "consultations.checkout.procedure": "Procedure:",
    "consultations.checkout.payment_method": "Payment Method",
    "consultations.checkout.multibanco": "Debit Card",
    "consultations.checkout.mbway": "Mobile Payment",
    "consultations.checkout.cash": "Cash",
    "consultations.checkout.transfer": "Bank Transfer",
    "consultations.checkout.send_email": "Send receipt via email",
    "consultations.checkout.email_ph": "Enter patient's email...",
    "consultations.checkout.cancel": "Cancel",
    "consultations.checkout.confirm": "Confirm Payment",
    "consultations.checkout.processing": "Processing...",
    "consultations.delete.title": "Attention!",
    "consultations.delete.desc": "Are you sure you want to cancel and delete this appointment? This action cannot be undone.",
    "consultations.delete.cancel": "Cancel",
    "consultations.delete.confirm": "Delete",
    "consultations.pdf.title": "FEE NOTE",
    "consultations.pdf.subtitle": "INTERNAL CONTROL DOCUMENT",
    "consultations.pdf.patient": "Patient: ",
    "consultations.pdf.datetime": "Date/Time: ",
    "consultations.pdf.procedure": "Procedure: ",
    "consultations.pdf.payment": "Payment Method: ",
    "consultations.pdf.total": "TOTAL PAID: ",
    "consultations.general": "General Consultation",
    "consultations.msg.updated": "Appointment updated!",
    "consultations.msg.scheduled": "Appointment scheduled!",
    "consultations.msg.save_err": "Error saving.",
    "consultations.msg.deleted": "Appointment deleted successfully.",
    "consultations.msg.delete_err": "Error deleting appointment.",
    "consultations.msg.checkout_success": "Appointment finished successfully!",
    "consultations.msg.checkout_err": "Error finishing on server.",
    "consultations.msg.comm_err": "Communication error.",
    "consultations.view.list": "List",
    "consultations.view.calendar": "Calendar",
    "consultations.checkout.materials": "Used Materials (Adjust if needed)",
    "consultations.checkout.no_materials": "No materials expected for this procedure.",
    "consultations.checkout.upload_exam": "Attach Exam / Document (Optional)",
    "consultations.checkout.rx_title": "Prescription & Recommendations (Optional)",
    "consultations.checkout.recs": "Post-Consultation Recommendations",
    "consultations.checkout.recs_ph": "E.g., Do not chew hard food for 2 hours. Apply ice...",
    "consultations.list.reminder": "Send Reminder (WhatsApp)",

    "users.title": "Access & Team",
    "users.subtitle": "Manage who has access to the clinic system.",
    "users.btn.add": "Add Member",
    "users.search.placeholder": "Search by name or email...",
    "users.card.you": "YOU",
    "users.card.offline": "OFFLINE",
    "users.card.role.assistant": "Assistant",
    "users.card.role.admin": "Admin",
    "users.card.tooltip.remove": "Remove User",
    "users.empty": "No users found with that search.",
    "users.delete.title": "Remove User?",
    "users.delete.desc": "This member's access will be permanently revoked.",
    "users.delete.cancel": "Cancel",
    "users.delete.confirm": "Remove",
    "users.modal.title": "New Member",
    "users.modal.name": "Full Name",
    "users.modal.name_ph": "Ex: Dr. Jane Doe",
    "users.modal.email": "Email Address",
    "users.modal.email_ph": "jane.doe@meclinic.com",
    "users.modal.pass": "Initial Password",
    "users.modal.pass_ph": "A password for the first login...",
    "users.modal.role": "System Role (Access)",
    "users.modal.role.assistant_desc": "Schedule & Appointments",
    "users.modal.role.admin_desc": "Full & Financial Access",
    "users.modal.cancel": "Cancel",
    "users.modal.create": "Create Member",
    "users.modal.creating": "Creating...",
    "users.mfa.title": "Mandatory Security (MFA)",
    "users.mfa.desc": "Member created. Ask this person to open the Google Authenticator App and scan this code right now.",
    "users.mfa.btn": "Finish Registration",
    "users.msg.del_self": "You cannot delete your own account while logged in.",
    "users.msg.removed": "User successfully removed from the system.",
    "users.msg.remove_err": "Error removing user.",
    "users.msg.added": "Member added successfully!",
    "users.msg.add_err": "Error creating user.",

    "billing.title": "History & Billing",
    "billing.subtitle": "Internal financial record of all finished appointments.",
    "billing.dashboard.total": "Total Charged",
    "billing.dashboard.processed": "processed appointments",
    "billing.filter.title": "Filter History",
    "billing.filter.today": "Today",
    "billing.filter.week": "Last 7 Days",
    "billing.filter.month": "This Month",
    "billing.filter.all": "All History",
    "billing.table.date": "DATE / TIME",
    "billing.table.patient": "PATIENT",
    "billing.table.procedure": "PROCEDURE",
    "billing.table.method": "METHOD",
    "billing.table.value": "VALUE",
    "billing.table.note": "NOTE",
    "billing.table.tooltip": "View Fee Note",
    "billing.table.empty": "No financial records found for this period.",
    "billing.modal.title": "Fee Note",
    "billing.modal.subtitle": "INTERNAL CONTROL DOCUMENT",
    "billing.modal.patient": "Patient:",
    "billing.modal.datetime": "Date & Time:",
    "billing.modal.procedure": "Procedure(s):",
    "billing.modal.method": "Payment Method:",
    "billing.modal.total": "TOTAL PAID",
    "billing.modal.btn_close": "Close",
    "billing.modal.btn_print": "Print Note",

    "reports.title": "Financial Report",
    "reports.subtitle": "Performance and cost analysis.",
    "reports.week_of": "Week of",
    "reports.btn.print": "Print Report",
    "reports.btn.send_email": "Send to Admin",
    "reports.btn.sending": "Sending...",
    "reports.card.consultations": "Completed Appointments",
    "reports.card.billed": "Total Billed",
    "reports.card.materials": "Material Cost",
    "reports.card.profit": "Estimated Gross Profit",
    "reports.table.procedures": "Procedures Performed",
    "reports.table.proc.name": "NAME",
    "reports.table.proc.qty": "QTY",
    "reports.table.proc.value": "BILLED VALUE",
    "reports.table.materials": "Material Consumption",
    "reports.table.mat.name": "MATERIAL",
    "reports.table.mat.qty": "QTY",
    "reports.table.mat.cost_un": "UNIT COST",
    "reports.table.mat.cost_total": "TOTAL COST",
    "reports.empty": "No data for this week.",
    "reports.loading": "Loading report data...",
    "reports.pdf.title": "Financial Summary",
    "reports.pdf.consultations": "Completed Appointments:",
    "reports.pdf.billed": "Total Billed:",
    "reports.pdf.materials": "Material Cost:",
    "reports.pdf.profit": "Estimated Gross Profit:",
    "reports.pdf.table.proc": "Procedure Performed",
    "reports.pdf.table.mat": "Material Used",
    "reports.msg.success": "Report sent successfully to your email",
    "reports.msg.email_err": "Error: Could not find your email in the database.",
    "reports.msg.send_err": "Error sending. Check the Gmail App Password on the server.",
    "reports.msg.server_err": "Failed to connect to the server.",
    "reports.alert.success": "Success!",
    "reports.alert.warning": "System Warning",
    "reports.alert.btn_ok": "OK, got it",

    "settings.title": "General Settings",
    "settings.subtitle": "Manage your preferences, interface, and account security.",
    "settings.tab.profile": "My Profile",
    "settings.tab.security": "Security & MFA",
    "settings.tab.appearance": "Appearance & Interface",
    "settings.tab.notifications": "Notifications",
    "settings.tab.clinic": "Clinic Data",
    "settings.profile.title": "My Profile",
    "settings.profile.avatar_desc": "Your photo is generated automatically based on your name.",
    "settings.profile.name": "Full Name",
    "settings.profile.email": "Email Address",
    "settings.profile.contact_admin": "Contact the Administrator to change sensitive account data.",
    "settings.security.title": "Security & Authentication",
    "settings.security.mfa_active": "2-Factor Authentication (MFA) Active",
    "settings.security.mfa_desc": "Your account is protected. The mobile device is required to make changes.",
    "settings.security.current_pass": "Current Password",
    "settings.security.new_pass": "New Password",
    "settings.security.confirm_pass": "Confirm New Password",
    "settings.security.mfa_code": "Google Authenticator Code",
    "settings.security.mfa_code_desc": "Enter the 6-digit code generated by the app.",
    "settings.security.placeholder.current": "••••••••",
    "settings.security.placeholder.new": "Min. 8 characters",
    "settings.security.placeholder.confirm": "Repeat password",
    "settings.appearance.title": "Appearance and Interface",
    "settings.appearance.theme": "System Theme",
    "settings.appearance.light": "Light Mode",
    "settings.appearance.light_desc": "Clean design for bright environments.",
    "settings.appearance.dark": "Dark Mode",
    "settings.appearance.dark_desc": "Focused environment that rests the eyes.",
    "settings.appearance.location": "Location",
    "settings.appearance.language": "Interface Language",
    "settings.appearance.time_format": "Time Format",
    "lang.pt": "Portuguese (Portugal)",
    "lang.en": "English (United States)",
    "lang.es": "Spanish (Spain)",
    "time.24h": "24 Hours (14:30)",
    "time.12h": "12 Hours (02:30 PM)",
    "settings.notif.title": "Alert Preferences",
    "settings.notif.stock": "Low Stock Alerts",
    "settings.notif.stock_desc": "Receive platform notifications when an item reaches the minimum limit.",
    "settings.notif.reports": "Weekly Financial Summary",
    "settings.notif.reports_desc": "Sends a PDF with the billing report to your email automatically every Friday.",
    "settings.notif.consultations": "Appointment Reminders",
    "settings.notif.consultations_desc": "Get a warning on your phone/computer 15 minutes before an appointment starts.",
    "settings.clinic.title": "Official Entity Data",
    "settings.clinic.readonly": "Read-Only Mode",
    "settings.clinic.entity_name": "Entity Name",
    "settings.clinic.nif": "Tax ID (VAT)",
    "settings.clinic.phone": "Main Phone",
    "settings.clinic.email": "General Email",
    "settings.clinic.address": "Full Address",
    "settings.clinic.address_desc": "This information is used in the header of Technical Sheets and Reports.",
    "settings.btn.save": "Save Changes",
    "settings.btn.update_security": "Update Security",
    "settings.alert.success": "Settings saved successfully!",
    "settings.alert.clinic_success": "Entity data updated successfully!",
    "settings.alert.pass_empty": "Please fill in all password fields.",
    "settings.alert.pass_mismatch": "The new password and confirmation do not match.",
    "settings.alert.mfa_empty": "Please enter the Google Authenticator code.",
    "settings.alert.server_error": "Error connecting to server.",
    "settings.privacy.title": "Privacy & GDPR Compliance",
    "settings.privacy.protection": "Data Protection",
    "settings.privacy.protection_desc": "Your data is protected in accordance with the General Data Protection Regulation (GDPR).",
    "settings.privacy.download": "Download Personal Data",
    "settings.privacy.download_desc": "Download a copy of all your personal data in JSON format.",
    "settings.privacy.delete": "Delete Account",
    "settings.privacy.delete_desc": "Deleting your account is permanent and will remove all your data from the system.",
    "settings.privacy.delete_confirm": "Delete Account Permanently",
    "settings.privacy.compliance": "Full GDPR Compliance",
    "settings.activity.title": "Account Activity",
    "settings.activity.sessions": "Active Sessions",
    "settings.activity.devices": "Connected Devices",
    "settings.activity.current_device": "This Device (current)",
    "settings.activity.logout_all": "Logout from All Devices",
    "settings.activity.history": "Recent Logins",
    "settings.activity.location": "Location",
    "settings.activity.device_info": "Device",

    "auth.login.title": "Welcome back",
    "auth.login.subtitle": "Enter your credentials to access.",
    "auth.login.email": "Email",
    "auth.login.pass": "Password",
    "auth.login.mfa": "Google Authenticator Code",
    "auth.login.btn": "Login to System",
    "auth.login.forgot": "Forgot your password?",
    "auth.register.title": "Create Account",
    "auth.register.subtitle": "Register on the clinic management portal.",
    "auth.register.name": "Full Name",
    "auth.register.btn": "Register Account",
    "auth.switch.login": "Already have an account? Login",
    "auth.switch.register": "Don't have an account? Register here",
    "auth.success.created": "Account successfully created!",
    "auth.success.mfa_desc": "Scan this QR Code with your Google Authenticator App to activate account security.",
    "auth.success.btn_login": "Go to Login",
    "auth.forgot.title": "Recover Password",
    "auth.forgot.subtitle": "Enter your email to receive a security code.",
    "auth.forgot.btn": "Send Code",
    "auth.forgot.back": "Back to Login",
    "auth.reset.title": "New Password",
    "auth.reset.subtitle": "Enter the code received in your email and the new password.",
    "auth.reset.code": "6-digit code",
    "auth.reset.new_pass": "New Password",
    "auth.reset.btn": "Change Password",
    "auth.reset.confirm_pass": "Confirm Password",
    "auth.reset.mismatch": "Passwords do not match.",

    // --- PACIENTES (CRM) ---
    "patients.title": "Patients",
    "patients.subtitle": "Clinical records and history management.",
    "patients.search": "Search patient...",
    "patients.table.name": "Name",
    "patients.table.contact": "Contact",
    "patients.table.consultations": "Visits",
    "patients.table.billed": "Billed",
    "patients.modal.info": "Patient Record",
    "patients.modal.notes": "Clinical Notes",
    "patients.modal.notes_ph": "Write allergies, medical history or treatment details here...",
    "patients.modal.history": "Consultation History",
    "patients.modal.save_notes": "Save Notes",
    "patients.modal.empty_history": "No consultations recorded.",
    "patients.tabs.history": "History",
    "patients.tabs.exams": "Exams & Files",
    "patients.exams.upload": "Attach File",
    "patients.exams.empty": "No files attached.",
    "patients.delete.btn": "Delete Patient",
    "patients.delete.confirm": "Are you sure? This will permanently delete the patient, consultations, and files.",
    "patients.table.actions": "Actions",
    "patients.rx.btn": "Issue Prescription",
    "patients.rx.title": "New Medical Prescription",
    "patients.rx.med": "Medication (e.g., Ibuprofen 600mg)",
    "patients.rx.dos": "Dosage (e.g., 1 pill every 8 hours)",
    "patients.rx.add": "Add Medication",
    "patients.rx.generate": "Generate & Save PDF",
  },
  es: {
    "app.logged_as": "Conectado como:",
    "sidebar.dashboard": "Panel de Control",
    "sidebar.inventory": "Inventario",
    "sidebar.consultations": "Consultas",
    "sidebar.technical_sheets": "Fichas Técnicas",
    "sidebar.users": "Usuarios",
    "sidebar.billing": "Facturación",
    "sidebar.reports": "Informes",
    "sidebar.light_mode": "Modo Claro",
    "sidebar.dark_mode": "Modo Oscuro",
    "sidebar.settings": "Ajustes",
    "sidebar.logout": "Cerrar sesión",
    "sidebar.patients": "Pacientes",

    "dashboard.title": "Panel MeClinic",
    "dashboard.subtitle": "Monitoreo de rendimiento semanal",
    "dashboard.week_of": "Semana del",
    "dashboard.card.new_patients": "NUEVOS PACIENTES",
    "dashboard.card.new_patients_sub": "Registrados esta semana",
    "dashboard.card.consultations": "CONSULTAS",
    "dashboard.card.consultations_sub": "Programadas para la semana",
    "dashboard.card.billing": "FACTURACIÓN ESTIMADA",
    "dashboard.card.billing_sub": "Basado en procedimientos",
    "dashboard.card.stock_alerts": "ALERTAS DE STOCK",
    "dashboard.card.stock_alerts_sub": "Productos por debajo del mínimo",
    "dashboard.chart.title": "Flujo de Pacientes por Día",
    "dashboard.modal.stock_title": "Productos en Alerta de Stock",
    "dashboard.modal.stock_desc": "Estos materiales han alcanzado o están por debajo del límite mínimo.",
    "dashboard.modal.table.product": "Producto",
    "dashboard.modal.table.current": "Stock Actual",
    "dashboard.modal.table.min": "Mínimo",
    "dashboard.modal.close": "Cerrar",
    "dashboard.modal.empty": "Ningún producto en alerta.",
    "dashboard.card.expiry_alerts": "ALERTAS CADUCIDAD",
    "dashboard.card.expiry_alerts_sub": "Caducan en < 30 días",
    "dashboard.modal.expiry_title": "Productos a Caducar",
    "dashboard.modal.expiry_desc": "Estos materiales caducarán en los próximos 30 días o ya han caducado.",
    "dashboard.modal.table.category": "Categoría",
    "dashboard.modal.table.expiry": "Caducidad",
    "dashboard.modal.btn_order": "Generar Pedido (PDF)",
    "dashboard.order.title": "NOTA DE PEDIDO",
    "dashboard.order.date": "Fecha:",
    "dashboard.order.product": "Producto",
    "dashboard.order.current": "Stock Actual",
    "dashboard.order.suggested": "Cant. a Pedir",
    "dashboard.order.signature": "Firma del Responsable:",

    "inventory.title": "Inventario",
    "inventory.subtitle": "Vista de tarjetas y escaneo de códigos de barras.",
    "inventory.btn.camera": "Escanear Código (Cámara)",
    "inventory.btn.add": "Añadir Producto",
    "inventory.search.placeholder": "Buscar producto o teclear código...",
    "inventory.card.no_code": "SIN CÓDIGO",
    "inventory.card.current_qty": "CANT. ACTUAL",
    "inventory.card.total_calc": "en total",
    "inventory.empty": "No se encontraron productos.",
    "inventory.modal.add_title": "Nuevo Producto",
    "inventory.modal.edit_title": "Editar Producto",
    "inventory.modal.name": "Nombre del Producto",
    "inventory.modal.name_ph": "Ej: Guantes de Nitrilo",
    "inventory.modal.barcode": "Código de Barras",
    "inventory.modal.barcode_ph": "Opcional...",
    "inventory.modal.unit": "Unidad de Medida",
    "inventory.modal.unit.un": "Unidades (un)",
    "inventory.modal.unit.cx": "Cajas (cx)",
    "inventory.modal.unit.mts": "Metros (m)",
    "inventory.modal.unit.lts": "Litros (L)",
    "inventory.modal.unit.ml": "Mililitros (ml)",
    "inventory.modal.unit.grs": "Gramos (g)",
    "inventory.modal.stock_current": "Stock Actual",
    "inventory.modal.stock_min": "Stock Mínimo (Alerta)",
    "inventory.modal.img_url": "URL de la Imagen (Enlace web)",
    "inventory.modal.img_url_ph": "https://...",
    "inventory.modal.cancel": "Cancelar",
    "inventory.modal.save": "Guardar",
    "inventory.delete.title": "¿Eliminar Producto?",
    "inventory.delete.desc": "Esta acción eliminará permanentemente el producto del inventario.",
    "inventory.delete.cancel": "Cancelar",
    "inventory.delete.confirm": "Eliminar",
    "inventory.alert.success": "¡Éxito!",
    "inventory.alert.warning": "Advertencia",
    "inventory.alert.btn_ok": "OK, entendido",
    "inventory.msg.removed": "Producto eliminado con éxito.",
    "inventory.msg.remove_err": "Error al eliminar producto.",
    "inventory.msg.server_err": "Fallo al conectar con el servidor.",
    "inventory.msg.added": "¡Producto añadido al inventario!",
    "inventory.msg.updated": "¡Producto actualizado!",
    "inventory.msg.save_err": "Error al guardar producto.",
    "inventory.cat.all": "Todas las Categorías",
    "inventory.cat.disposables": "Desechables",
    "inventory.cat.anesthesia": "Anestesia y Fármacos",
    "inventory.cat.endo": "Endo y Restauración",
    "inventory.cat.surgery": "Cirugía e Implantes",
    "inventory.cat.ortho": "Ortodoncia",
    "inventory.cat.sterilization": "Esterilización",
    "inventory.cat.instruments": "Instrumentos",
    "inventory.modal.category": "Categoría del Producto",
    "inventory.modal.expiry": "Fecha de Caducidad",
    "inventory.modal.expiry_ph": "Opcional...",

    "tech_sheets.title": "Fichas Técnicas",
    "tech_sheets.btn.new": "Nuevo Procedimiento",
    "tech_sheets.list.price": "Precio Venta:",
    "tech_sheets.list.empty": "No hay procedimientos creados.",
    "tech_sheets.modal.new_title": "Nuevo Procedimento",
    "tech_sheets.modal.new_ph": "Nombre de la ficha técnica...",
    "tech_sheets.modal.cancel": "Cancelar",
    "tech_sheets.modal.create": "Crear",
    "tech_sheets.delete.title": "¿Borrar Procedimiento?",
    "tech_sheets.delete.desc_part1": "¿Estás seguro de que quieres eliminar la ficha de",
    "tech_sheets.delete.desc_part2": "Esta acción elimina los materiales asociados.",
    "tech_sheets.delete.remove": "Eliminar",
    "tech_sheets.detail.edit": "Editar",
    "tech_sheets.detail.remove": "Eliminar",
    "tech_sheets.detail.export": "Exportar PDF",
    "tech_sheets.detail.cancel": "Cancelar",
    "tech_sheets.detail.save": "Guardar Cambios",
    "tech_sheets.table.material": "Material Utilizado",
    "tech_sheets.table.qty": "Cant.",
    "tech_sheets.table.cost_un": "Costo Un.",
    "tech_sheets.table.subtotal": "Subtotal",
    "tech_sheets.table.ph_material": "Nombre del material...",
    "tech_sheets.btn.add_material": "Añadir Nuevo Material",
    "tech_sheets.summary.cost": "Costo Materiales",
    "tech_sheets.summary.price": "Precio a Cobrar",
    "tech_sheets.empty_state.title": "Ninguna ficha seleccionada",
    "tech_sheets.empty_state.desc": "Seleccione un procedimiento de la lista a la izquierda para ver los materiales y costos.",
    "tech_sheets.msg.created": "¡Procedimiento creado!",
    "tech_sheets.msg.removed": "¡Procedimiento eliminado con éxito!",
    "tech_sheets.msg.remove_err": "Error al eliminar procedimiento.",
    "tech_sheets.msg.saved": "¡Ficha actualizada y guardada!",
    "tech_sheets.msg.save_err": "Error al guardar la ficha técnica.",

    "consultations.title": "Gestión de Consultas",
    "consultations.form.new": "Nueva Cita",
    "consultations.form.edit": "Editar Cita",
    "consultations.form.name_ph": "Nombre del Paciente",
    "consultations.form.email_ph": "Correo (Recomendado)",
    "consultations.form.phone_ph": "Ej: 912345678",
    "consultations.form.procedure": "Procedimiento Clínico",
    "consultations.form.procedure_ph": "Seleccione un procedimiento...",
    "consultations.form.date": "Fecha",
    "consultations.form.time": "Hora",
    "consultations.form.notes": "Notas Adicionales...",
    "consultations.form.notes_ph": "Opcional...",
    "consultations.form.btn_confirm": "Confirmar Cita",
    "consultations.form.btn_save": "Guardar Cambios",
    "consultations.form.btn_cancel": "Cancelar Edición",
    "consultations.list.title": "Citas",
    "consultations.list.filter_today": "Hoy",
    "consultations.list.filter_week": "7 Días",
    "consultations.list.filter_month": "30 Días",
    "consultations.list.empty": "No se encontraron citas para este período.",
    "consultations.list.finished": "Finalizada",
    "consultations.list.no_procedure": "Sin Procedimiento",
    "consultations.list.no_phone": "Sin número",
    "consultations.tooltip.finish": "Finalizar Consulta",
    "consultations.tooltip.edit": "Editar",
    "consultations.tooltip.delete": "Anular Cita",
    "consultations.checkout.title": "Finalizar Consulta",
    "consultations.checkout.patient": "Paciente:",
    "consultations.checkout.procedure": "Procedimiento:",
    "consultations.checkout.payment_method": "Método de Pago",
    "consultations.checkout.multibanco": "Tarjeta de Débito",
    "consultations.checkout.mbway": "MB Way",
    "consultations.checkout.cash": "Efectivo",
    "consultations.checkout.transfer": "Transferencia Bancaria",
    "consultations.checkout.send_email": "Enviar recibo por correo",
    "consultations.checkout.email_ph": "Introduzca el correo del paciente...",
    "consultations.checkout.cancel": "Cancelar",
    "consultations.checkout.confirm": "Confirmar Pago",
    "consultations.checkout.processing": "Procesando...",
    "consultations.delete.title": "¡Atención!",
    "consultations.delete.desc": "¿Estás seguro de que deseas anular y eliminar esta cita? Esta acción no se puede deshacer.",
    "consultations.delete.cancel": "Cancelar",
    "consultations.delete.confirm": "Eliminar",
    "consultations.pdf.title": "NOTA DE HONORARIOS",
    "consultations.pdf.subtitle": "DOCUMENTO DE CONTROL INTERNO",
    "consultations.pdf.patient": "Paciente: ",
    "consultations.pdf.datetime": "Fecha/Hora: ",
    "consultations.pdf.procedure": "Procedimiento: ",
    "consultations.pdf.payment": "Método Pago: ",
    "consultations.pdf.total": "TOTAL PAGADO: ",
    "consultations.general": "Consulta General",
    "consultations.msg.updated": "¡Cita actualizada!",
    "consultations.msg.scheduled": "¡Cita programada!",
    "consultations.msg.save_err": "Error al guardar.",
    "consultations.msg.deleted": "Cita eliminada con éxito.",
    "consultations.msg.delete_err": "Error al eliminar cita.",
    "consultations.msg.checkout_success": "¡Consulta finalizada con éxito!",
    "consultations.msg.checkout_err": "Error al finalizar en el servidor.",
    "consultations.msg.comm_err": "Error de comunicación.",
    "consultations.view.list": "Lista",
    "consultations.view.calendar": "Calendario",
    "consultations.checkout.materials": "Materiales Utilizados (Ajuste si es necesario)",
    "consultations.checkout.no_materials": "Ningún material previsto para este procedimiento.",
    "consultations.checkout.upload_exam": "Adjuntar Examen / Documento (Opcional)",
    "consultations.checkout.rx_title": "Receta y Recomendaciones (Opcional)",
    "consultations.checkout.recs": "Recomendaciones Post-Consulta",
    "consultations.checkout.recs_ph": "Ej: No masticar alimentos duros en 2h. Aplicar hielo...",
    "consultations.list.reminder": "Enviar Recordatorio (WhatsApp)",

    "users.title": "Accesos y Equipo",
    "users.subtitle": "Gestiona quién tiene acceso al sistema de la clínica.",
    "users.btn.add": "Añadir Miembro",
    "users.search.placeholder": "Buscar por nombre o correo...",
    "users.card.you": "TÚ",
    "users.card.offline": "DESCONECTADO",
    "users.card.role.assistant": "Asistente",
    "users.card.role.admin": "Admin",
    "users.card.tooltip.remove": "Eliminar Usuario",
    "users.empty": "No se encontraron usuarios con esa búsqueda.",
    "users.delete.title": "¿Eliminar Usuario?",
    "users.delete.desc": "El acceso de este miembro será revocado permanentemente.",
    "users.delete.cancel": "Cancelar",
    "users.delete.confirm": "Eliminar",
    "users.modal.title": "Nuevo Miembro",
    "users.modal.name": "Nombre Completo",
    "users.modal.name_ph": "Ej: Dra. Ana Silva",
    "users.modal.email": "Correo Electrónico",
    "users.modal.email_ph": "ana.silva@meclinic.com",
    "users.modal.pass": "Contraseña Inicial",
    "users.modal.pass_ph": "Una contraseña para el primer acceso...",
    "users.modal.role": "Función en el Sistema (Acceso)",
    "users.modal.role.assistant_desc": "Agenda y Consultas",
    "users.modal.role.admin_desc": "Acceso Total y Financiero",
    "users.modal.cancel": "Cancelar",
    "users.modal.create": "Crear Miembro",
    "users.modal.creating": "Creando...",
    "users.mfa.title": "Seguridad Obligatoria (MFA)",
    "users.mfa.desc": "Miembro creado. Pídale a esta persona que abra la App Google Authenticator y escanee este código ahora mismo.",
    "users.mfa.btn": "Finalizar Registro",
    "users.msg.del_self": "No puedes eliminar tu propia cuenta mientras estás conectado.",
    "users.msg.removed": "Usuario eliminado del sistema con éxito.",
    "users.msg.remove_err": "Error al eliminar usuario.",
    "users.msg.added": "¡Miembro añadido con éxito!",
    "users.msg.add_err": "Error al crear usuario.",

    "billing.title": "Historial y Facturación",
    "billing.subtitle": "Registro financiero interno de todas las consultas finalizadas.",
    "billing.dashboard.total": "Total Cobrado",
    "billing.dashboard.processed": "consultas procesadas",
    "billing.filter.title": "Filtrar Historial",
    "billing.filter.today": "Hoy",
    "billing.filter.week": "Últimos 7 Días",
    "billing.filter.month": "Este Mes",
    "billing.filter.all": "Todo el Historial",
    "billing.table.date": "FECHA / HORA",
    "billing.table.patient": "PACIENTE",
    "billing.table.procedure": "PROCEDIMIENTO",
    "billing.table.method": "MÉTODO",
    "billing.table.value": "VALOR",
    "billing.table.note": "NOTA",
    "billing.table.tooltip": "Ver Nota de Honorarios",
    "billing.table.empty": "No se encontraron registros financieros para este período.",
    "billing.modal.title": "Nota de Honorarios",
    "billing.modal.subtitle": "DOCUMENTO DE CONTROL INTERNO",
    "billing.modal.patient": "Paciente:",
    "billing.modal.datetime": "Fecha y Hora:",
    "billing.modal.procedure": "Procedimiento(s):",
    "billing.modal.method": "Método Pago:",
    "billing.modal.total": "TOTAL PAGADO",
    "billing.modal.btn_close": "Cerrar",
    "billing.modal.btn_print": "Imprimir Nota",

    "reports.title": "Informe Financiero",
    "reports.subtitle": "Análisis de rendimiento y costos.",
    "reports.week_of": "Semana del",
    "reports.btn.print": "Imprimir Informe",
    "reports.btn.send_email": "Enviar a Admin",
    "reports.btn.sending": "Enviando...",
    "reports.card.consultations": "Consultas Completadas",
    "reports.card.billed": "Total Facturado",
    "reports.card.materials": "Costo de Materiales",
    "reports.card.profit": "Beneficio Bruto Estimado",
    "reports.table.procedures": "Procedimientos Realizados",
    "reports.table.proc.name": "NOMBRE",
    "reports.table.proc.qty": "CANT.",
    "reports.table.proc.value": "VALOR FACTURADO",
    "reports.table.materials": "Consumo de Materiales",
    "reports.table.mat.name": "MATERIAL",
    "reports.table.mat.qty": "CANT.",
    "reports.table.mat.cost_un": "COSTO UN.",
    "reports.table.mat.cost_total": "COSTO TOTAL",
    "reports.empty": "No hay datos para esta semana.",
    "reports.loading": "Cargando datos del informe...",
    "reports.pdf.title": "Resumen Financiero",
    "reports.pdf.consultations": "Consultas Completadas:",
    "reports.pdf.billed": "Total Facturado:",
    "reports.pdf.materials": "Costo de Materiales:",
    "reports.pdf.profit": "Beneficio Bruto Estimado:",
    "reports.pdf.table.proc": "Procedimiento Realizado",
    "reports.pdf.table.mat": "Material Gastado",
    "reports.msg.success": "Informe enviado con éxito a su correo electrónico",
    "reports.msg.email_err": "Error: No se pudo encontrar su correo en la base de datos.",
    "reports.msg.send_err": "Error al enviar. Compruebe la contraseña de la aplicación Gmail en el servidor.",
    "reports.msg.server_err": "Fallo al conectar con el servidor.",
    "reports.alert.success": "¡Éxito!",
    "reports.alert.warning": "Advertencia del Sistema",
    "reports.alert.btn_ok": "OK, entendido",

    "settings.title": "Configuración General",
    "settings.subtitle": "Gestiona tus preferencias, interfaz y seguridad de la cuenta.",
    "settings.tab.profile": "Mi Perfil",
    "settings.tab.security": "Seguridad y MFA",
    "settings.tab.appearance": "Apariencia e Interfaz",
    "settings.tab.notifications": "Notificaciones",
    "settings.tab.clinic": "Datos de la Clínica",
    "settings.profile.title": "Mi Perfil",
    "settings.profile.avatar_desc": "Tu foto se genera automáticamente en base a tu nombre.",
    "settings.profile.name": "Nombre Completo",
    "settings.profile.email": "Correo Electrónico",
    "settings.profile.contact_admin": "Contacta al Administrador para alterar datos sensibles.",
    "settings.security.title": "Seguridad y Autenticación",
    "settings.security.mfa_active": "Autenticación de 2 Factores (MFA) Activa",
    "settings.security.mfa_desc": "Tu cuenta está protegida. El móvil es obligatorio para realizar cambios.",
    "settings.security.current_pass": "Contraseña Actual",
    "settings.security.new_pass": "Nueva Contraseña",
    "settings.security.confirm_pass": "Confirmar Nueva",
    "settings.security.mfa_code": "Código Google Authenticator",
    "settings.security.mfa_code_desc": "Introduce el código de 6 dígitos generado por la aplicación.",
    "settings.security.placeholder.current": "••••••••",
    "settings.security.placeholder.new": "Mín. 8 caracteres",
    "settings.security.placeholder.confirm": "Repita la contraseña",
    "settings.appearance.title": "Apariencia e Interfaz",
    "settings.appearance.theme": "Tema del Sistema",
    "settings.appearance.light": "Modo Claro",
    "settings.appearance.light_desc": "Diseño limpio para entornos iluminados.",
    "settings.appearance.dark": "Modo Oscuro",
    "settings.appearance.dark_desc": "Entorno enfocado que descansa la vista.",
    "settings.appearance.location": "Ubicación",
    "settings.appearance.language": "Idioma de la Interfaz",
    "settings.appearance.time_format": "Formato de Hora",
    "lang.pt": "Portugués (Portugal)",
    "lang.en": "Inglés (Estados Unidos)",
    "lang.es": "Español (España)",
    "time.24h": "24 Horas (14:30)",
    "time.12h": "12 Horas (02:30 PM)",
    "settings.notif.title": "Preferencias de Alertas",
    "settings.notif.stock": "Alertas de Stock Bajo",
    "settings.notif.stock_desc": "Recibe notificaciones en la plataforma cuando un material alcanza el límite mínimo.",
    "settings.notif.reports": "Resumen Financiero Semanal",
    "settings.notif.reports_desc": "Envía un PDF con el informe de facturación a tu correo automáticamente todos los viernes.",
    "settings.notif.consultations": "Recordatorios de Consultas",
    "settings.notif.consultations_desc": "Recibe un aviso en el móvil/ordenador 15 minutos antes de empezar una consulta.",
    "settings.clinic.title": "Datos Oficiales de la Entidad",
    "settings.clinic.readonly": "Modo Lectura",
    "settings.clinic.entity_name": "Nombre de la Entidad",
    "settings.clinic.nif": "NIF",
    "settings.clinic.phone": "Teléfono Principal",
    "settings.clinic.email": "Correo General",
    "settings.clinic.address": "Dirección Completa",
    "settings.clinic.address_desc": "Esta información se utiliza en el encabezado de Fichas Técnicas e Informes.",
    "settings.btn.save": "Guardar Cambios",
    "settings.btn.update_security": "Actualizar Seguridad",
    "settings.alert.success": "¡Configuración guardada con éxito!",
    "settings.alert.clinic_success": "¡Datos de la entidad actualizados!",
    "settings.alert.pass_empty": "Rellene todos los campos de la contraseña.",
    "settings.alert.pass_mismatch": "La nueva contraseña y la confirmación no coinciden.",
    "settings.alert.mfa_empty": "Por favor, introduzca el código de Google Authenticator.",
    "settings.alert.server_error": "Error al conectar con el servidor.",
    "settings.privacy.title": "Privacidad y Cumplimiento RGPD",
    "settings.privacy.protection": "Protección de Datos",
    "settings.privacy.protection_desc": "Tus datos están protegidos de acuerdo con el Reglamento General de Protección de Datos (RGPD).",
    "settings.privacy.download": "Descargar Datos Personales",
    "settings.privacy.download_desc": "Descarga una copia de todos tus datos personales en formato JSON.",
    "settings.privacy.delete": "Eliminar Cuenta",
    "settings.privacy.delete_desc": "Eliminar tu cuenta es permanente y eliminará todos tus datos del sistema.",
    "settings.privacy.delete_confirm": "Eliminar Cuenta Permanentemente",
    "settings.privacy.compliance": "Cumplimiento Total de RGPD",
    "settings.activity.title": "Actividad de la Cuenta",
    "settings.activity.sessions": "Sesiones Activas",
    "settings.activity.devices": "Dispositivos Conectados",
    "settings.activity.current_device": "Este Dispositivo (actual)",
    "settings.activity.logout_all": "Cerrar Sesión en Todos los Dispositivos",
    "settings.activity.history": "Inicios de Sesión Recientes",
    "settings.activity.location": "Ubicación",
    "settings.activity.device_info": "Dispositivo",

    "auth.login.title": "Bienvenido de nuevo",
    "auth.login.subtitle": "Introduzca sus credenciales para acceder.",
    "auth.login.email": "Correo Electrónico",
    "auth.login.pass": "Contraseña",
    "auth.login.mfa": "Código Google Authenticator",
    "auth.login.btn": "Entrar al Sistema",
    "auth.login.forgot": "¿Olvidó su contraseña?",
    "auth.register.title": "Crear Cuenta",
    "auth.register.subtitle": "Regístrate en el portal de gestión clínica.",
    "auth.register.name": "Nombre Completo",
    "auth.register.btn": "Registrar Cuenta",
    "auth.switch.login": "¿Ya tienes una cuenta? Iniciar Sesión",
    "auth.switch.register": "¿No tienes cuenta? Regístrate aquí",
    "auth.success.created": "¡Cuenta creada con éxito!",
    "auth.success.mfa_desc": "Escanea este código QR con tu aplicación Google Authenticator para activar la seguridad de la cuenta.",
    "auth.success.btn_login": "Ir a Iniciar Sesión",
    "auth.forgot.title": "Recuperar Contraseña",
    "auth.forgot.subtitle": "Introduzca su correo para recibir un código de seguridad.",
    "auth.forgot.btn": "Enviar Código",
    "auth.forgot.back": "Volver al Inicio",
    "auth.reset.title": "Nueva Contraseña",
    "auth.reset.subtitle": "Introduzca el código recibido y su nueva contraseña.",
    "auth.reset.code": "Código de 6 dígitos",
    "auth.reset.new_pass": "Nueva Contraseña",
    "auth.reset.btn": "Cambiar Contraseña",
    "auth.reset.confirm_pass": "Confirmar Contraseña",
    "auth.reset.mismatch": "Las contraseñas no coinciden.",

    // --- PACIENTES (CRM) ---
    "patients.title": "Pacientes",
    "patients.subtitle": "Gestión de fichas clínicas e historial.",
    "patients.search": "Buscar paciente...",
    "patients.table.name": "Nombre",
    "patients.table.contact": "Contacto",
    "patients.table.consultations": "Visitas",
    "patients.table.billed": "Facturado",
    "patients.modal.info": "Ficha del Paciente",
    "patients.modal.notes": "Notas Clínicas",
    "patients.modal.notes_ph": "Escriba aquí alergias, historial médico o detalles de tratamientos...",
    "patients.modal.history": "Historial de Consultas",
    "patients.modal.save_notes": "Guardar Notas",
    "patients.modal.empty_history": "No hay consultas registradas.",
    "patients.tabs.history": "Historial",
    "patients.tabs.exams": "Exámenes y Archivos",
    "patients.exams.upload": "Adjuntar Archivo",
    "patients.exams.empty": "Ningún archivo adjunto.",
    "patients.delete.btn": "Eliminar Paciente",
    "patients.delete.confirm": "¿Estás seguro? Esto borrará permanentemente al paciente, consultas y archivos.",
    "patients.table.actions": "Acciones",
    "patients.rx.btn": "Emitir Receta",
    "patients.rx.title": "Nueva Receta Médica",
    "patients.rx.med": "Medicamento (ej: Ibuprofeno 600mg)",
    "patients.rx.dos": "Dosis (ej: 1 comp. cada 8 horas)",
    "patients.rx.add": "Añadir Medicamento",
    "patients.rx.generate": "Generar y Guardar PDF",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('meclinic_lang') || 'pt';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('meclinic_lang', lang);
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};